Features/order
HAt0r1/rising-stars-project pull request #1
Opened 2023-11-25 12:45 UTC by HalynkaSavchenko

2023-11-25 14:30 UTC, HAt0r1 requested changes

2023-11-25 14:30 UTC, HAt0r1 commented on src/partials/order.html
> +        <div class="background-wrapper"></div>
`<div class="background-wrapper></div>"` повинен бути після `<section class="order">`

2023-11-25 14:30 UTC, HAt0r1 commented on src/partials/order.html
> +    <div class="container form-wrapper">
`<div class="form-container container">` повинен бути після ` <div class="background-wrapper"></div>`

2023-11-25 14:30 UTC, HAt0r1 commented on src/partials/order.html
> +        <h2><span class="text-order">Your order</span> is our priority: Personalized approach and quality of service</h2>
Задайте класс `<h2>` наприклад "title-order"

2023-11-25 14:30 UTC, HAt0r1 commented on src/css/order.css
> +.background-wrapper {
Для правильного відображення background-image скористайтеся " max-width: 100%;
  height: 550px;
  background-image: url(../img/order-img/image-mobile.jpg);
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;
  margin-bottom: 80px;"

2023-11-25 14:30 UTC, HAt0r1 commented on src/css/order.css
> +
Додайте `.order` з ` padding-top: 40px;
  padding-bottom: 40px;`

2023-11-25 14:30 UTC, HAt0r1 commented on src/css/order.css
> +.background-wrapper {
Краще задайте wrapper не в @media а просто винести їх

2023-11-26 13:17 UTC, HAt0r1 requested changes
Також я додам вам у папку img зображення, яке треба буде зробити як background-img

2023-11-26 13:17 UTC, HAt0r1 commented on src/css/order.css
> +    justify-content: center;
Поставьте значення ` justify-content: flex-start;`

2023-11-26 13:17 UTC, HAt0r1 commented on src/css/order.css
> +    align-items: center;
Поставьте значення `align-items: flex-start;`

2023-11-26 13:17 UTC, HAt0r1 commented on src/css/order.css
> +    width: 375px;
Поставьте width: 100%

2023-11-26 13:17 UTC, HAt0r1 commented on src/css/order.css
> +    gap: 8px;
gap повинен бути - `gap: 20px`

2023-11-26 13:17 UTC, HAt0r1 commented on src/css/order.css
> +.order-image {
Додати до `.order-image { border-radius: 4px}` і також додати `padding-bottom: 79px`

2023-11-26 13:17 UTC, HAt0r1 commented on src/css/order.css
> +    margin-left: 66px;
Замість `margin-left: 66px;` поставьте `padding-left: 66px;`

2023-11-26 13:17 UTC, HAt0r1 commented on src/css/order.css
> +gap: 20px;
Видалити цю строку

2023-11-26 13:17 UTC, HAt0r1 commented on src/css/order.css
> +.order-image {
Додати `object-fit: cover;` та додати `padding-left:0`. Також додати `padding-bottom:119px`

2023-11-26 15:00 UTC, HalynkaSavchenko commented on src/css/order.css
> +    justify-content: center;
ok

2023-11-26 15:00 UTC, HalynkaSavchenko commented on src/css/order.css
> +    align-items: center;
ok

2023-11-26 15:01 UTC, HalynkaSavchenko commented on src/css/order.css
> +    width: 375px;
ok

2023-11-26 15:03 UTC, HalynkaSavchenko commented on src/css/order.css
> +    gap: 8px;
ok

2023-11-26 15:05 UTC, HalynkaSavchenko commented on src/css/order.css
> +.order-image {
ok

2023-11-26 15:08 UTC, HalynkaSavchenko commented on src/css/order.css
> +    margin-left: 66px;
ok

2023-11-26 15:08 UTC, HalynkaSavchenko commented on src/css/order.css
> +gap: 20px;
ok

2023-11-26 15:12 UTC, HalynkaSavchenko commented on src/css/order.css
> +.order-image {
ok

2023-11-26 15:24 UTC, HAt0r1 requested changes
Додати у background-image на секції визирунок

2023-11-26 15:29 UTC, HalynkaSavchenko commented
Добре, мені треба, щоб ти змержив цей пулл реквест, щоб я могла зробити нову гілку з візерунком в папці. Бо зараз в моїй гілці немає цього візерунка

2023-11-26 16:01 UTC, HAt0r1 approved these changes

2023-11-26 16:01 UTC, merged