Feature/order background png
HAt0r1/rising-stars-project pull request #10
Opened 2023-11-26 16:40 UTC by HalynkaSavchenko

2023-11-26 16:55 UTC, HAt0r1 requested changes

2023-11-26 16:55 UTC, HAt0r1 commented on src/css/order.css
> +
Додати `background-size: 484px 545px`

2023-11-26 16:55 UTC, HAt0r1 commented on src/css/order.css
> +    background-position: left 0px bottom 50px;
У `background-position` треба у `bottom` вказати значення -70px

2023-11-26 16:55 UTC, HAt0r1 commented on src/css/order.css
> +    background-position: left -35px bottom 75px;
Треба вказати: ` background-position: left -35px bottom 75px`;

2023-11-26 17:36 UTC, HAt0r1 requested changes

2023-11-26 17:36 UTC, HAt0r1 commented on src/css/order.css
> +..order {
Має бути `.order`

2023-11-26 18:36 UTC, HalynkaSavchenko commented on src/css/order.css
> +
Додала background-size: 484px 545px в медіа для екранів з щільністю 2

2023-11-26 18:37 UTC, HalynkaSavchenko commented on src/css/order.css
> +    background-position: left 0px bottom 50px;
Тут бекграунд позиціонувала відносно секції, від нижнього краю на 50 пикселів. Ніби все вірно

2023-11-26 18:38 UTC, HalynkaSavchenko commented on src/css/order.css
> +    background-position: left -35px bottom 75px;
Так і вказано

2023-11-26 18:38 UTC, HalynkaSavchenko commented on src/css/order.css
> +..order {
О, дякую, виправила

2023-11-27 10:31 UTC, HAt0r1 approved these changes
Все добре зроблено

2023-11-27 10:31 UTC, merged