Feature/setup hero. Add tablet+desktop hero
HAt0r1/rising-stars-project pull request #5
Opened 2023-11-26 01:48 UTC by VictoriaKiselova

2023-11-27 02:14 UTC, VictoriaKiselova commented
change hero

2023-11-27 12:56 UTC, HAt0r1 requested changes
Робота виконана добре, будь-ласка зробіть виправлення

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +@media screen and (min-width: 320px), (max-width: 375px) {
Не треба було видаляти .container з reset. Будь-ласка зробіть у reset.css у самому низу` .container { padding-left: 20px; padding-right: 20px; margin 0 auto;}` а цей видаліть. І просто у медіа задасте `@media screen and (min-width:375px) {.container {max-width:375px}}`

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    background: #1c2225;
У нас по стилям вже стоїть колір на background, тому видаліть його

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    padding-top: 60px;
У хедері було прописано `padding-bottom: 50px `, тому вам треба замінити ваш `padding-top: 60px;` на `padding-top: 10px;`

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    color: var(--white, #fcf9f9);
Можна прибрати color та font-weight, бо вони підтягуються зі стилів

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    font-weight: 400;
Можна прибрати font-weight

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    height: 49px;
Можна прибрати height

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    flex-direction: row;
По дефолту стоїть значення row, це не помилка, але можна прибрати

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    margin-left: 70px;
На жаль, ми не можемо використовувати у данному випадку `margin-left`, краще зробіть до кнопки стилі для класу `.ukraine-style-box {
 display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}`

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    background: url(<path-to-image>), lightgray 50% / cover no-repeat;
Можете будь-ласка прибрати url(<path-toimage>) та залишити все інше

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    margin-left: auto;
Коли додасте контейнер до reset.css, у подальшому можете не задавати margin

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    width: 768px;
max-width: 768px;

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    padding-top: 106px;
`padding-top: 53px;`

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    letter-spacing: -0.03em;
Воно наслідується, можна не додавати це

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    margin-left: 141px;
Видалити `margin-left: 141px;`

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +  }
Додати до медіа клас .ukraine-style-box {  justify-content: flex-start; align-items: flex-start }

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    background: url(<path-to-image>),
Прибрати `url(<path-to-image>)`

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    display: flex;
Видалити display: flex, та ще 3 строки знизу: `flex-direction, align-items, gap`

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    font-size: 16px;
Можна видалити font-size, font-weight, line-height

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    width: 1280px;
max-width: 1280px

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    margin-right: auto;
Прибрати margin-left та margin-right

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    padding-top: 100px;
Прибрати padding-top

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +    padding-top: 94px;
Прибрати padding-top, та замість нього написати `justify-content: center;
    align-items: center;`

2023-11-27 12:56 UTC, HAt0r1 commented on src/css/hero.css
> +  }
Сюди додати стилі до класу ` .ukrainian-embroidery-box {
    right: 100px;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: 16px;
  }`

2023-11-27 13:05 UTC, VictoriaKiselova commented on src/css/hero.css
> +    background: #1c2225;
+

2023-11-27 13:25 UTC, VictoriaKiselova commented on src/css/hero.css
> +    padding-top: 60px;
Так у хедера нет по макету падинга в 50рх. А по идее если же будет изменяться бекграунд на секции hero, эти 50px сверху не относятся к  хедеру. Это по  паддинг секции Hero. Иначе при изменении бекграунда будет: хедер--паддинг50рх--только потом секция Hero с новым бекграундом?

2023-11-27 13:52 UTC, VictoriaKiselova commented on src/css/hero.css
> +    margin-right: auto;
+

2023-11-27 14:19 UTC, VictoriaKiselova commented on src/css/hero.css
> +    padding-top: 94px;
+

2023-11-27 14:23 UTC, VictoriaKiselova commented on src/css/hero.css
> +    color: var(--white, #fcf9f9);
+

2023-11-27 15:28 UTC, HAt0r1 requested changes
Передивіться помилки. Ви не все виправили.

2023-11-27 20:39 UTC, HAt0r1 approved these changes

2023-11-27 20:39 UTC, merged

2023-11-28 16:06 UTC, VictoriaKiselova commented on src/css/hero.css
> +@media screen and (min-width: 320px), (max-width: 375px) {
+

2023-11-28 16:08 UTC, VictoriaKiselova commented on src/css/hero.css
> +    font-weight: 400;
В таком случае заголовок будет отличаться от макета.

2023-11-28 16:11 UTC, VictoriaKiselova commented on src/css/hero.css
> +    padding-top: 100px;
+

2023-11-28 16:12 UTC, VictoriaKiselova commented on src/css/hero.css
> +  }
Это картинка.